#clear
#EXEC=/sf/sisma/exec
#INCLUD=/sf/sisma/includes
#FUEN1=/sf/sisma/src
#OBJ=/sf/sisma/obj

#CFLAGS="-I/sf/sisma/include -DSUN_OS -DUNIX -DTRAZA=20"; export CC CFLAGS 
#CC=cc CFLAGS="-I/sf/sisma/includes"; export CC CFLAGS

#buildclient -o pmanejTux -f /sf/sisma/src/pmanejTux.c -f "$/sf/sisma/obj/filefun.o /sf/sisma/obj/libisma.a"

#SOL_CC= "cc -m64 -DSUN_OS -DUNIX -DTRAZA=20 -DTUXEDO"


##UNIX_LIB=/sf/sisma/obj/filefun.o -L/opt/oracle/product/12.1.0/client_1/lib -I/opt/tuxedo/tuxedo12.2.2.0.0/include -lclntsh
##UNIX_INCS=-I/sf/sisma/include -I${TUXDIR}/include
##BUILDCLIENT=${TUXDIR}/bin/buildclient
##
##pmanejTux : /sf/sisma/obj/pmanejTux.o  /sf/sisma/obj/libsisma.a
##	cc -m64 -I/sf/sisma/include -o pmanejTux /sf/sisma/obj/pmanejTux.o /sf/sisma/obj/libsisma.a  -L/opt/oracle/product/12.1.0/client_1/lib -lnsl -lclntsh -I/opt/tuxedo/tuxedo12.2.2.0.0/include -I/opt/tuxedo/tuxedo12.2.2.0.0/include /opt/tuxedo/tuxedo12.2.2.0.0/bin/buildclient 
##	mv pmanejTux /sf/sisma/exec/pmanejTux
##	chmod 777 /sf/sisma/exec/pmanejTux
##
##/sf/sisma/obj/pmanejTux.o: /sf/sisma/src/pmanejTux.c
##	cc -m64 -c -DSUN_OS -DUNIX -I/sf/sisma/include /sf/sisma/src/pmanejTux.c -I/opt/tuxedo/tuxedo12.2.2.0.0/include
##	mv pmanejTux.o /sf/sisma/obj/
##	chmod 777 /sf/sisma/obj/pmanejTux.o
##
/sf/sisma/exec/pmanejTux: /sf/sisma/obj/pmanejTux.o  /sf/sisma/obj/libsisma.a
	cc -m64 -o /sf/sisma/exec/pmanejTux /sf/sisma/obj/pmanejTux.o /sf/sisma/obj/libsisma.a -L/opt/oracle/product/12.1.0/client_1/lib -lnsl -I/opt/tuxedo/tuxedo12.2.2.0.0/include -L/opt/tuxedo/tuxedo12.2.2.0.0/bin/buildclient 
	chmod 777  /sf/sisma/exec/pmanejTux

/sf/sisma/obj/pmanejTux.o: /sf/sisma/src/pmanejTux.c
	cc -m64 -c -O -I/sf/sisma/includes /sf/sisma/src/pmanejTux.c -lsisma -L/opt/oracle/product/12.1.0/client_1/lib -lnsl -I/opt/tuxedo/tuxedo12.2.2.0.0/include -L/opt/tuxedo/tuxedo12.2.2.0.0/bin/buildclient 
	mv pmanejTux.o /sf/sisma/obj
	chmod 777  /sf/sisma/obj/pmanejTux.o
