void  amplia_Q(int cola,int tamano); 
int   bin2hex(char * pcadena, int numerico, int * longi); 
int   borrarSVM(char *nomsvm,char *pars);
void  borra_cola(int q_id);
int   borrar_svm(int shmid);
int   busca_en_svm(SVM *psvm_par,int pos,int tipo);
int   busca_proc_svm(SVM *psvm_par,char *proce,pid_t auxpid);
int   buscar_si_habitual(char *pcodden);
int   buscar_si_repetida(formato_interno *pforitn,int sesion);
int   busca_svmbin(tbbine *PsvmBine, char *pbinope); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
int   busca_svmtibi(tbtibi *psvmtibi,int NUMTIEN, char *ptieope, char *pterope, char *ptipope);
int   campo_hexadecimal (char * campo);
int   campo_numerico (char * campo);
void  carga_bin(tbbine *pbine,NPSBINE rbin); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
int   carga_bines(tbbine *psvmbine); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
int   carga_bines(tbtibi *psvmtibi); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
int   carga_bines(tbtibi *psvmtibi); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
int   carga_bines(tbtibi *tb_tibi);  //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
char  carga_colas(char *cdcola,int *tamano);
int   carga_reso(tbreso *psvmreso);
int   carga_socks(tbsock *psvmsock);
void  carga_subs(SVM *Psvm,NPSPARS *reg);
int   carga_tibis(tbtibi *psvmtibi);
int   carga_tien();
void  carga_un_reso(tbreso *preso,NPSRESO regreso);
long  centlong();
int   cmpstr(char *buf1,char *buf2,int len);
int   comp_fec(char *f1,char *f2);
int   ConecSVMaux1(void *gen_psvm,int shmid);
int   ConecSVMaux(void **gen_psvm,int shmid);
int   crear_svmbine(tbbine **gen_psvm,int *shmid,int operacion); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
int   crear_svmreso(tbreso **gen_psvm,int *shmid,int operacion);
int   crear_svmsock(void **gen_psvm,int *shmid,int operacion);
int   crear_svmtibi(tbtibi **gen_psvm,int *shmid,int operacion);
int   crearSVM(void **gen_psvm,int *shmid,int operacion,char *nomsvm);
int   cuenta_reg(NOMFICH fich);
int   damecola(SVM *psvm_par,char *proce,char *subsis);
void  dame_campos(char * regent, char separador,int ncampo, char * resultado, int *lencampo);
int   Dame_info_svm(SVM *psvm_par,char *aux,int tipo_B,int quedan);
key_t dame_llave(char clave);
int   dame_posisvmsock(tbsock *psvmsock);
int   dame_posisvmsock(tbsock *psvmsock);
int   dame_seg(char *buf);
int   desconec_svm(void *pun_svm);
char  *dtoa(double valor);
int   encuentra_svm(SVM *psvm_par,char *aux,int tipo);
int   envconso(int graved, char *liter,formato_interno *pforitn);
int   envconsoof(int graved, char *liter,formato_interno *pforitn);
int   EnviaCola(int cola,int timeout,char *Datosmsg,int Lenmsg,int Tipomsg);
int   envia_fin_cola(SVM *regsvm);
int   EnviaSock(int sfd,int timeout,char *msg,int len);
int   espera_preparado(SVM * psvm_pro);
int   Fcargatbop();
int   fconvres(formato_interno *pfi);
int   fdateg(char *sfechaj, char *sfechag);
int   fdatej(char *sfechag,char *sfechaj);
int   fdesempa(int longi,char *sempaq,char *sdesem);
int   fdesepin(int longi, char *sempaq, char *sdesem);
int   fdiferencia_en_diasg(fecha * pgreg_ini, fecha * pgreg_fin, int * diferencia);
int   fdiferencia_en_diasj(juliana * pjul_ini, juliana * pjul_fin, int * pdiferencia);
int   fempapin(int longi, char *sempaq, char *sdesem);
int   fempaque(int longi,char *sempaq,char *sdesem);
int   fgraba_incidencia_cp(char * coderr, char *numope, char *nompro, char *nomfic);
int   fgregoriana(juliana * fechaj,fecha * fechag);
void  fhexdump(FILE * pf, void * vaddr, int len);
int   finalizar(int codigo);
int   finfoenv(NPSINEN  reg_inen,char *nomfic);
int   fjuliana(fecha *fechag,juliana *fechaj);
void  flog(FILE * pf, char * msg, ...);
int   fmonta_claves16 (formato_interno *pforitn);
int   fnumlog(char chLog, stres_numlog * presp);
int   fnumope (char *numope);
ttbop *Fnuevotb();
int   Fordentb();
int   ftime(struct timeb *loc_tp);
int   graba_automata(NPSINCI reginci) ;
int   graba_denegada(formato_interno *pforitn);
int   haz_demonio(char * proceso, int numero);
int   hex2bin(char * pcadena, int * numerico, int longi);
void  hexdump(char * addr, int len);
void  inicfori (int tipomsg, formato_interno *pfi);
int   isnstr(char *buf,char c,int len);
int   isstr (char *buf,char c);
int   lanzar_proc(char proce[NUM_PROCES][11], SVM * psvm);
void  lee_error(char *codigo, char * literal);
int   LeerCola(int cola,int timeout,char *Datosmsg,int Lonmsg,int Tipomsg);
int   LeerSock(int sfd,int timeout,char *msg,int len);
int   limpia_qsvm(SVM *psvm,char *para);
void  limpia_bin(tbbine *Svmbine); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
void  limpia_bin(tbbine *Svmbine); //Comprobado que no afecta para PRJ0202598 cambio bin de 6 posiciones 8
void  limpia_reso(tbreso *preso);
void  limpia_reso(tbreso *preso);
void  limpia_tbsock(tbsock *pp);
void  limpia_tbsock(tbsock *pp);
void  limpia_tbtibi(Listatbtibi *elem);
void  limpia_tbtibi(Listatbtibi *elem);
void  limpia_tbtibi(tbtibi *tb_tibi,int inicio,int fin);
void  limpia_tibi(tbtibi *Svmtibi);
void  limpiar_struc(void *pstr,int tam);
void  localtime1(tm_dec *tm2);
void  lpad(char *bufer,char c,int lon);
void  ltrim(char *bufer,char c);
void  marca_alarma(int sig);
int   mayorstr(char *buf1,char *buf2,int len);
void  mueve_tbtibi(Listatbtibi *elem,NPSTIBI reg_tibi);
int   ncampo_hexadecimal (char *c,int n);
int   ncampo_numerico (char *c,int n);
int   nlow_values (char *c,int n);
int   nmdlow_values (char *c,int n);
int   no_exis_qsvm(SVM *psvm_par,int posi);
int   nspaces (char *c,int n);
int   parar_subsis(SVM *psvm_par,char *para,int pos_subsis);
int   parar_todo(SVM *psvm_par);
void  pasaSVM(Listatbtibi *Ptbtibi,tbtibi *psvmtibi); 
void  pinta_decimal(float buf, int ndec,char *resultado);
char  *pone_barras_fecha(char *buf) ;
void  pone_coma_decimal(int ent, int dec, char *buf, char * resultado) ;
int   posicion_tienda(tbtibi *Psvmt,int NUMTIEN,char *ptieope,int *donde);
int   potencia(int base, int exponente);
void  quita_coma_decimal(char * buf,char * resultado);
int   resolutor_fecha(NPSTIBI * regtibi,char * fechahoy, char * resfec_aux);
void  rpad(char *bufer,char c,int lon);
void  rtrim(char *bufer,char c);
void  salir(char *para,int tipo,int error,int shmid,SVM *psvm, char * nombre);
void  sigue();
int   spaces (char *c);
void  strchg(char *buf,char in,char out);
void  strnchg(char *buf,char in,char out,int len);
int   trata_colas(char cola,int tamano,int *idcola);
void  uMinusculas ( char * pcCadena );
int   valida_fechaj (juliana * pfecha);
int   ver_fi(FILE * fic,formato_interno fi);
int   Xusleep(unsigned int micro_seg);
